// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      aciklama: json['aciklama'] as String?,
      ad: json['ad'] as String?,
      adres: json['adres'] as String?,
      aidat: json['aidat'] as int?,
      altBransId: json['altBransId'] as int?,
      anneAd: json['anneAd'] as String?,
      antrenorId: json['antrenorId'] as int?,
      babaAd: json['babaAd'] as String?,
      bakiye: (json['bakiye'] as num?)?.toDouble(),
      basTarih: json['basTarih'] as String?,
      bitTarih: json['bitTarih'] as String?,
      bransId: json['bransId'] as int?,
      createDate: json['createDate'] as String?,
      createUserId: json['createUserId'] as int?,
      dogumTarihi: json['dogumTarihi'] as String?,
      durum: json['durum'] as int?,
      ekDers: (json['ekDers'] as num?)?.toDouble(),
      email: json['email'] as String?,
      foto: json['foto'] as String?,
      hesKodu: json['hesKodu'] as String?,
      id: json['id'] as int?,
      indirimli: json['indirimli'] as int?,
      izinBasTarih: json['izinBasTarih'] as String?,
      izindenDonusTarih: json['izindenDonusTarih'] as String?,
      kartNumarasi: json['kartNumarasi'] as String?,
      kayitTarihi: json['kayitTarihi'] as String?,
      kusakId: json['kusakId'] as int?,
      kutlamaSmsYil: json['kutlamaSmsYil'] as int?,
      lisansNo: json['lisansNo'] as String?,
      lisansYil: json['lisansYil'] as int?,
      meslek: json['meslek'] as String?,
      odemeGunu: json['odemeGunu'] as String?,
      paket: json['paket'] as int?,
      soyad: json['soyad'] as String?,
      tc: json['tc'] as String?,
      tel1: json['tel1'] as String?,
      tel2: json['tel2'] as String?,
      tutar: json['tutar'] as int?,
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'aciklama': instance.aciklama,
      'ad': instance.ad,
      'adres': instance.adres,
      'aidat': instance.aidat,
      'altBransId': instance.altBransId,
      'anneAd': instance.anneAd,
      'antrenorId': instance.antrenorId,
      'babaAd': instance.babaAd,
      'bakiye': instance.bakiye,
      'basTarih': instance.basTarih,
      'bitTarih': instance.bitTarih,
      'bransId': instance.bransId,
      'createDate': instance.createDate,
      'createUserId': instance.createUserId,
      'dogumTarihi': instance.dogumTarihi,
      'durum': instance.durum,
      'ekDers': instance.ekDers,
      'email': instance.email,
      'foto': instance.foto,
      'hesKodu': instance.hesKodu,
      'id': instance.id,
      'indirimli': instance.indirimli,
      'izinBasTarih': instance.izinBasTarih,
      'izindenDonusTarih': instance.izindenDonusTarih,
      'kartNumarasi': instance.kartNumarasi,
      'kayitTarihi': instance.kayitTarihi,
      'kusakId': instance.kusakId,
      'kutlamaSmsYil': instance.kutlamaSmsYil,
      'lisansNo': instance.lisansNo,
      'lisansYil': instance.lisansYil,
      'meslek': instance.meslek,
      'odemeGunu': instance.odemeGunu,
      'paket': instance.paket,
      'soyad': instance.soyad,
      'tc': instance.tc,
      'tel1': instance.tel1,
      'tel2': instance.tel2,
      'tutar': instance.tutar,
    };
